services:

  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tests
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    build:
      context: app
    links:
      - db
      - adminer
    environment:
      - DATABASE_URL=postgresql+psycopg_async://admin:admin@db/postgres
    stop_signal: SIGKILL
    restart: always
    ports:
      - "8000:8000"
